In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('bank.csv')

In [3]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1
5,42,4,2,2,0,0,1,1,2,5,8,562,2,-1,0,3,1
6,56,4,1,2,0,830,1,1,2,6,8,1201,1,-1,0,3,1
7,60,5,0,1,0,545,1,0,2,6,8,1030,1,-1,0,3,1
8,37,9,1,1,0,1,1,0,2,6,8,608,1,-1,0,3,1
9,28,7,2,1,0,5090,1,0,2,6,8,1297,3,-1,0,3,1
10,38,0,2,1,0,100,1,0,2,7,8,786,1,-1,0,3,1
11,30,1,1,1,0,309,1,0,2,7,8,1574,2,-1,0,3,1
12,29,4,1,2,0,199,1,1,2,7,8,1689,4,-1,0,3,1
13,46,1,2,2,0,460,1,0,2,7,8,1102,2,-1,0,3,1
14,31,9,2,2,0,703,1,0,2,8,8,943,2,-1,0,3,1
15,35,4,0,2,0,3837,1,0,2,8,8,1084,1,-1,0,3,1
16,32,1,2,0,0,611,1,0,2,8,8,541,3,-1,0,3,1
17,49,7,1,1,0,-8,1,0,2,8,8,1119,1,-1,0,3,1
18,41,0,1,1,0,55,1,0,2,8,8,1120,2,-1,0,3,1
19,49,0,0,1,0,168,1,1,2,8,8,513,1,-1,0,3,1
20,28,0,0,1,0,785,1,0,2,8,8,442,2,-1,0,3,1
21,43,4,2,2,0,2067,1,0,2,8,8,756,1,-1,0,3,1
22,43,4,0,2,0,388,1,0,2,8,8,2087,2,-1,0,3,1
23,43,1,1,0,0,-192,1,0,2,8,8,1120,2,-1,0,3,1
24,37,10,2,1,0,381,1,0,2,8,8,985,2,-1,0,3,1
25,35,1,2,1,0,40,1,0,2,9,8,617,4,-1,0,3,1
26,31,9,2,2,0,22,1,0,2,9,8,483,3,-1,0,3,1
27,43,1,2,1,0,3,1,0,2,9,8,929,3,-1,0,3,1
28,31,0,1,1,0,307,1,0,2,9,8,538,1,-1,0,3,1
29,28,1,2,1,0,759,1,0,2,9,8,710,1,-1,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11132,32,1,1,1,0,-325,1,1,2,21,8,171,1,-1,0,3,0
11133,37,4,1,2,0,1594,1,0,0,17,0,110,1,260,5,0,0
11134,58,6,1,2,0,2596,0,0,1,18,9,15,2,-1,0,3,0
11135,36,7,0,1,0,115,0,0,2,6,6,201,1,-1,0,3,0
11136,31,4,2,2,0,0,1,0,0,8,11,76,1,-1,0,3,0
11137,49,5,1,3,0,247,0,0,2,15,8,213,2,-1,0,3,0
11138,32,9,1,1,0,235,1,0,1,28,1,688,6,-1,0,3,0
11139,30,6,2,2,0,2593,0,0,2,27,8,662,7,-1,0,3,0
11140,55,7,0,1,0,2166,1,0,2,28,8,23,17,-1,0,3,0
11141,32,1,1,1,0,130,1,0,0,6,8,302,2,-1,0,3,0
11142,52,0,0,1,0,48,0,1,0,17,9,591,1,-1,0,3,0
11143,38,10,0,1,0,189,1,1,0,21,5,105,2,-1,0,3,0
11144,60,5,1,1,0,0,1,0,2,15,8,229,1,-1,0,3,0
11145,60,5,0,2,0,-134,0,0,0,12,8,243,1,271,4,0,0
11146,30,0,1,1,1,23,0,1,0,4,3,149,2,-1,0,3,0
11147,44,10,1,1,0,0,0,0,0,21,9,175,4,-1,0,3,0
11148,32,1,1,1,0,1,1,0,2,8,8,102,1,-1,0,3,0
11149,46,2,1,1,0,3317,0,0,0,19,9,231,2,-1,0,3,0
11150,34,4,1,1,0,355,0,0,0,21,1,314,3,-1,0,3,0
11151,40,4,1,2,0,917,1,0,2,20,8,292,1,-1,0,3,0
11152,34,3,1,1,0,390,1,0,0,15,5,659,3,-1,0,3,0
11153,43,0,2,1,0,35,0,0,1,9,9,208,1,-1,0,3,0
11154,52,9,1,2,0,523,1,1,0,8,5,113,1,-1,0,3,0
11155,35,1,1,1,0,80,1,1,0,21,9,38,2,172,2,0,0
11156,34,1,2,1,0,-72,1,0,0,7,5,273,5,-1,0,3,0
11157,33,1,2,0,0,1,1,0,0,20,0,257,1,-1,0,3,0
11158,39,7,1,1,0,733,0,0,2,16,6,83,4,-1,0,3,0
11159,32,9,2,1,0,29,0,0,0,19,1,156,2,-1,0,3,0
11160,43,9,1,1,0,0,0,1,0,8,8,9,2,172,5,0,0
11161,34,9,1,1,0,0,0,0,0,9,5,628,1,-1,0,3,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null int64
marital      11162 non-null int64
education    11162 non-null int64
default      11162 non-null int64
balance      11162 non-null int64
housing      11162 non-null int64
loan         11162 non-null int64
contact      11162 non-null int64
day          11162 non-null int64
month        11162 non-null int64
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null int64
deposit      11162 non-null int64
dtypes: int64(17)
memory usage: 1.4 MB

In [7]:
for i in df:
    print(i)
    print('\n')
    print(df[i].value_counts)
    print('\n')

age


<bound method IndexOpsMixin.value_counts of 0        59
1        56
2        41
3        55
4        54
5        42
6        56
7        60
8        37
9        28
10       38
11       30
12       29
13       46
14       31
15       35
16       32
17       49
18       41
19       49
20       28
21       43
22       43
23       43
24       37
25       35
26       31
27       43
28       31
29       28
         ..
11132    32
11133    37
11134    58
11135    36
11136    31
11137    49
11138    32
11139    30
11140    55
11141    32
11142    52
11143    38
11144    60
11145    60
11146    30
11147    44
11148    32
11149    46
11150    34
11151    40
11152    34
11153    43
11154    52
11155    35
11156    34
11157    33
11158    39
11159    32
11160    43
11161    34
Name: age, Length: 11162, dtype: int64>


job


<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         9
3         7
4         0
5         4
6         4
7         5
8         9
9         7
10        0
11        1
12        4
13        1
14        9
15        4
16        1
17        7
18        0
19        0
20        0
21        4
22        4
23        1
24       10
25        1
26        9
27        1
28        0
29        1
         ..
11132     1
11133     4
11134     6
11135     7
11136     4
11137     5
11138     9
11139     6
11140     7
11141     1
11142     0
11143    10
11144     5
11145     5
11146     0
11147    10
11148     1
11149     2
11150     4
11151     4
11152     3
11153     0
11154     9
11155     1
11156     1
11157     1
11158     7
11159     9
11160     9
11161     9
Name: job, Length: 11162, dtype: int64>


marital


<bound method IndexOpsMixin.value_counts of 0        1
1        1
2        1
3        1
4        1
5        2
6        1
7        0
8        1
9        2
10       2
11       1
12       1
13       2
14       2
15       0
16       2
17       1
18       1
19       0
20       0
21       2
22       0
23       1
24       2
25       2
26       2
27       2
28       1
29       2
        ..
11132    1
11133    1
11134    1
11135    0
11136    2
11137    1
11138    1
11139    2
11140    0
11141    1
11142    0
11143    0
11144    1
11145    0
11146    1
11147    1
11148    1
11149    1
11150    1
11151    1
11152    1
11153    2
11154    1
11155    1
11156    2
11157    2
11158    1
11159    2
11160    1
11161    1
Name: marital, Length: 11162, dtype: int64>


education


<bound method IndexOpsMixin.value_counts of 0        1
1        1
2        1
3        1
4        2
5        2
6        2
7        1
8        1
9        1
10       1
11       1
12       2
13       2
14       2
15       2
16       0
17       1
18       1
19       1
20       1
21       2
22       2
23       0
24       1
25       1
26       2
27       1
28       1
29       1
        ..
11132    1
11133    2
11134    2
11135    1
11136    2
11137    3
11138    1
11139    2
11140    1
11141    1
11142    1
11143    1
11144    1
11145    2
11146    1
11147    1
11148    1
11149    1
11150    1
11151    2
11152    1
11153    1
11154    2
11155    1
11156    1
11157    0
11158    1
11159    1
11160    1
11161    1
Name: education, Length: 11162, dtype: int64>


default


<bound method IndexOpsMixin.value_counts of 0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
11132    0
11133    0
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    0
11143    0
11144    0
11145    0
11146    1
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    0
11155    0
11156    0
11157    0
11158    0
11159    0
11160    0
11161    0
Name: default, Length: 11162, dtype: int64>


balance


<bound method IndexOpsMixin.value_counts of 0        2343
1          45
2        1270
3        2476
4         184
5           0
6         830
7         545
8           1
9        5090
10        100
11        309
12        199
13        460
14        703
15       3837
16        611
17         -8
18         55
19        168
20        785
21       2067
22        388
23       -192
24        381
25         40
26         22
27          3
28        307
29        759
         ...
11132    -325
11133    1594
11134    2596
11135     115
11136       0
11137     247
11138     235
11139    2593
11140    2166
11141     130
11142      48
11143     189
11144       0
11145    -134
11146      23
11147       0
11148       1
11149    3317
11150     355
11151     917
11152     390
11153      35
11154     523
11155      80
11156     -72
11157       1
11158     733
11159      29
11160       0
11161       0
Name: balance, Length: 11162, dtype: int64>


housing


<bound method IndexOpsMixin.value_counts of 0        1
1        0
2        1
3        1
4        0
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
11132    1
11133    1
11134    0
11135    0
11136    1
11137    0
11138    1
11139    0
11140    1
11141    1
11142    0
11143    1
11144    1
11145    0
11146    0
11147    0
11148    1
11149    0
11150    0
11151    1
11152    1
11153    0
11154    1
11155    1
11156    1
11157    1
11158    0
11159    0
11160    0
11161    0
Name: housing, Length: 11162, dtype: int64>


loan


<bound method IndexOpsMixin.value_counts of 0        0
1        0
2        0
3        0
4        0
5        1
6        1
7        0
8        0
9        0
10       0
11       0
12       1
13       0
14       0
15       0
16       0
17       0
18       0
19       1
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
11132    1
11133    0
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    1
11143    1
11144    0
11145    0
11146    1
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    1
11155    1
11156    0
11157    0
11158    0
11159    0
11160    1
11161    0
Name: loan, Length: 11162, dtype: int64>


contact


<bound method IndexOpsMixin.value_counts of 0        2
1        2
2        2
3        2
4        2
5        2
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       2
17       2
18       2
19       2
20       2
21       2
22       2
23       2
24       2
25       2
26       2
27       2
28       2
29       2
        ..
11132    2
11133    0
11134    1
11135    2
11136    0
11137    2
11138    1
11139    2
11140    2
11141    0
11142    0
11143    0
11144    2
11145    0
11146    0
11147    0
11148    2
11149    0
11150    0
11151    2
11152    0
11153    1
11154    0
11155    0
11156    0
11157    0
11158    2
11159    0
11160    0
11161    0
Name: contact, Length: 11162, dtype: int64>


day


<bound method IndexOpsMixin.value_counts of 0         5
1         5
2         5
3         5
4         5
5         5
6         6
7         6
8         6
9         6
10        7
11        7
12        7
13        7
14        8
15        8
16        8
17        8
18        8
19        8
20        8
21        8
22        8
23        8
24        8
25        9
26        9
27        9
28        9
29        9
         ..
11132    21
11133    17
11134    18
11135     6
11136     8
11137    15
11138    28
11139    27
11140    28
11141     6
11142    17
11143    21
11144    15
11145    12
11146     4
11147    21
11148     8
11149    19
11150    21
11151    20
11152    15
11153     9
11154     8
11155    21
11156     7
11157    20
11158    16
11159    19
11160     8
11161     9
Name: day, Length: 11162, dtype: int64>


month


<bound method IndexOpsMixin.value_counts of 0         8
1         8
2         8
3         8
4         8
5         8
6         8
7         8
8         8
9         8
10        8
11        8
12        8
13        8
14        8
15        8
16        8
17        8
18        8
19        8
20        8
21        8
22        8
23        8
24        8
25        8
26        8
27        8
28        8
29        8
         ..
11132     8
11133     0
11134     9
11135     6
11136    11
11137     8
11138     1
11139     8
11140     8
11141     8
11142     9
11143     5
11144     8
11145     8
11146     3
11147     9
11148     8
11149     9
11150     1
11151     8
11152     5
11153     9
11154     5
11155     9
11156     5
11157     0
11158     6
11159     1
11160     8
11161     5
Name: month, Length: 11162, dtype: int64>


duration


<bound method IndexOpsMixin.value_counts of 0        1042
1        1467
2        1389
3         579
4         673
5         562
6        1201
7        1030
8         608
9        1297
10        786
11       1574
12       1689
13       1102
14        943
15       1084
16        541
17       1119
18       1120
19        513
20        442
21        756
22       2087
23       1120
24        985
25        617
26        483
27        929
28        538
29        710
         ...
11132     171
11133     110
11134      15
11135     201
11136      76
11137     213
11138     688
11139     662
11140      23
11141     302
11142     591
11143     105
11144     229
11145     243
11146     149
11147     175
11148     102
11149     231
11150     314
11151     292
11152     659
11153     208
11154     113
11155      38
11156     273
11157     257
11158      83
11159     156
11160       9
11161     628
Name: duration, Length: 11162, dtype: int64>


campaign


<bound method IndexOpsMixin.value_counts of 0         1
1         1
2         1
3         1
4         2
5         2
6         1
7         1
8         1
9         3
10        1
11        2
12        4
13        2
14        2
15        1
16        3
17        1
18        2
19        1
20        2
21        1
22        2
23        2
24        2
25        4
26        3
27        3
28        1
29        1
         ..
11132     1
11133     1
11134     2
11135     1
11136     1
11137     2
11138     6
11139     7
11140    17
11141     2
11142     1
11143     2
11144     1
11145     1
11146     2
11147     4
11148     1
11149     2
11150     3
11151     1
11152     3
11153     1
11154     1
11155     2
11156     5
11157     1
11158     4
11159     2
11160     2
11161     1
Name: campaign, Length: 11162, dtype: int64>


pdays


<bound method IndexOpsMixin.value_counts of 0         -1
1         -1
2         -1
3         -1
4         -1
5         -1
6         -1
7         -1
8         -1
9         -1
10        -1
11        -1
12        -1
13        -1
14        -1
15        -1
16        -1
17        -1
18        -1
19        -1
20        -1
21        -1
22        -1
23        -1
24        -1
25        -1
26        -1
27        -1
28        -1
29        -1
        ...
11132     -1
11133    260
11134     -1
11135     -1
11136     -1
11137     -1
11138     -1
11139     -1
11140     -1
11141     -1
11142     -1
11143     -1
11144     -1
11145    271
11146     -1
11147     -1
11148     -1
11149     -1
11150     -1
11151     -1
11152     -1
11153     -1
11154     -1
11155    172
11156     -1
11157     -1
11158     -1
11159     -1
11160    172
11161     -1
Name: pdays, Length: 11162, dtype: int64>


previous


<bound method IndexOpsMixin.value_counts of 0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
11132    0
11133    5
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    0
11143    0
11144    0
11145    4
11146    0
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    0
11155    2
11156    0
11157    0
11158    0
11159    0
11160    5
11161    0
Name: previous, Length: 11162, dtype: int64>


poutcome


<bound method IndexOpsMixin.value_counts of 0        3
1        3
2        3
3        3
4        3
5        3
6        3
7        3
8        3
9        3
10       3
11       3
12       3
13       3
14       3
15       3
16       3
17       3
18       3
19       3
20       3
21       3
22       3
23       3
24       3
25       3
26       3
27       3
28       3
29       3
        ..
11132    3
11133    0
11134    3
11135    3
11136    3
11137    3
11138    3
11139    3
11140    3
11141    3
11142    3
11143    3
11144    3
11145    0
11146    3
11147    3
11148    3
11149    3
11150    3
11151    3
11152    3
11153    3
11154    3
11155    0
11156    3
11157    3
11158    3
11159    3
11160    0
11161    3
Name: poutcome, Length: 11162, dtype: int64>


deposit


<bound method IndexOpsMixin.value_counts of 0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
11132    0
11133    0
11134    0
11135    0
11136    0
11137    0
11138    0
11139    0
11140    0
11141    0
11142    0
11143    0
11144    0
11145    0
11146    0
11147    0
11148    0
11149    0
11150    0
11151    0
11152    0
11153    0
11154    0
11155    0
11156    0
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64>

In [8]:
df['job'].median()

4.0

In [10]:
Q1=df['job'].quantile(0.25)
Q2=df['job'].quantile(0.5)
Q3=df['job'].quantile(0.75)
Q4=df['job'].quantile(1)

In [14]:
Q4

11.0

In [16]:
df.describe()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,4.487905,1.199337,1.285164,0.015051,1528.538524,0.473123,0.130801,0.489697,15.658036,5.445709,371.993818,2.508421,51.330407,0.832557,2.477782,0.473840
std,11.913369,3.225132,0.625552,0.749478,0.121761,3225.413326,0.499299,0.337198,0.818724,8.420740,3.191939,347.128386,2.722077,108.758282,2.292007,1.002952,0.499338
min,18.000000,0.000000,0.000000,0.000000,0.000000,-6847.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,-1.000000,0.000000,0.000000,0.000000
25%,32.000000,1.000000,1.000000,1.000000,0.000000,122.000000,0.000000,0.000000,0.000000,8.000000,3.000000,138.000000,1.000000,-1.000000,0.000000,2.000000,0.000000
50%,39.000000,4.000000,1.000000,1.000000,0.000000,550.000000,0.000000,0.000000,0.000000,15.000000,6.000000,255.000000,2.000000,-1.000000,0.000000,3.000000,0.000000
75%,49.000000,7.000000,2.000000,2.000000,0.000000,1708.000000,1.000000,0.000000,1.000000,22.000000,8.000000,496.000000,3.000000,20.750000,1.000000,3.000000,1.000000
max,95.000000,11.000000,2.000000,3.000000,1.000000,81204.000000,1.000000,1.000000,2.000000,31.000000,11.000000,3881.000000,63.000000,854.000000,58.000000,3.000000,1.000000

In [17]:
IQR=Q3-Q1

In [18]:
IQR

6.0

# Calculating the variance

In [19]:
#Calculate the mean
mean=df['job'].mean()

In [30]:
#Calculate the difference between the value with mean.you will get the distance
difference=df['job']-mean

In [31]:
#square the distance
squared_diff=difference**2

In [32]:
#calculate the sum of variance obtained
variance=sum(squared_diff)

In [33]:
#Calculate the average of variance
variance=variance/len(df['job'])

In [28]:
variance

10.400543561020113

In [29]:
df['job'].var()

10.40147542586744